sudo: required
services:
  - docker

before_install:
  - docker build -t shaunxenonkhan/docker-react -f Dockerfile.dev .

script:
  - docker run shaunxenonkhan/docker-react npm run test -- --coverage
